services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: always
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api
    restart: unless-stopped
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"

volumes:
  pgdata:
