FROM python:3.12-slim

WORKDIR /api
RUN pip install --no-cache-dir uv

COPY pyproject.toml ./
COPY uv.lock* ./

RUN uv sync --locked

ENV PATH="/api/.venv/bin:$PATH"

COPY . .

EXPOSE 8000

ENTRYPOINT ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
